local function callback()
  return {
    AerialArray = { fg = C.ui.text },
    AerialArrayIcon = { link = "@constant" },
    AerialBoolean = { fg = C.ui.text },
    AerialBooleanIcon = { link = "@boolean" },
    AerialClass = { fg = C.ui.text },
    AerialClassIcon = { link = "@type" },
    AerialConstant = { fg = C.ui.text },
    AerialConstantIcon = { link = "@constant" },
    AerialConstructor = { fg = C.ui.text },
    AerialConstructorIcon = { link = "@constructor" },
    AerialEnum = { fg = C.ui.text },
    AerialEnumIcon = { link = "@type" },
    AerialEnumMember = { fg = C.ui.text },
    AerialEnumMemberIcon = { link = "@field" },
    AerialEvent = { fg = C.ui.text },
    AerialEventIcon = { link = "@type" },
    AerialField = { fg = C.ui.text },
    AerialFieldIcon = { link = "@field" },
    AerialFile = { fg = C.ui.text },
    AerialFileIcon = { link = "@text.uri" },
    AerialFunction = { fg = C.ui.text },
    AerialFunctionIcon = { link = "@function" },
    AerialGuide = { fg = C.ui.none_text },
    AerialInterface = { fg = C.ui.text },
    AerialInterfaceIcon = { link = "@type" },
    AerialKey = { fg = C.ui.text },
    AerialKeyIcon = { link = "@type" },
    AerialLine = { fg = C.ui.accent, bg = C.none },
    AerialMethod = { fg = C.ui.text },
    AerialMethodIcon = { link = "@method" },
    AerialModule = { fg = C.ui.text },
    AerialModuleIcon = { link = "@namespace" },
    AerialNamespace = { fg = C.ui.text },
    AerialNamespaceIcon = { link = "@namespace" },
    AerialNull = { fg = C.ui.text },
    AerialNullIcon = { link = "@type" },
    AerialNumber = { fg = C.ui.text },
    AerialNumberIcon = { link = "@number" },
    AerialObject = { fg = C.ui.text },
    AerialObjectIcon = { link = "@type" },
    AerialOperator = { fg = C.ui.text },
    AerialOperatorIcon = { link = "@operator" },
    AerialPackage = { fg = C.ui.text },
    AerialPackageIcon = { link = "@namespace" },
    AerialProperty = { fg = C.ui.text },
    AerialPropertyIcon = { link = "@property" },
    AerialString = { fg = C.ui.text },
    AerialStringIcon = { link = "@string" },
    AerialStruct = { fg = C.ui.text },
    AerialStructIcon = { link = "@type" },
    AerialType = { fg = C.ui.text },
    AerialTypeIcon = { link = "@type" },
    AerialTypeParameter = { fg = C.ui.text },
    AerialTypeParameterIcon = { link = "@parameter" },
    AerialVariable = { fg = C.ui.text },
    AerialVariableIcon = { link = "@variable" },
  }
end

return callback
