return {
  ["aerial.nvim"] = "aerial",
  ["beacon.nvim"] = "beacon",
  ["bufferline.nvim"] = "bufferline",
  ["dashboard-nvim"] = "dashboard-nvim",
  ["gitsigns.nvim"] = "gitsigns",
  ["hop.nvim"] = "hop",
  ["indent-blankline.nvim"] = "indent-blankline",
  ["lightspeed.nvim"] = "lightspeed",
  ["neo-tree.nvim"] = "neo-tree",
  ["nvim-cmp"] = "nvim-cmp",
  ["nvim-dap-ui"] = "nvim-dap-ui",
  ["nvim-notify"] = "nvim-notify",
  ["nvim-tree.lua"] = "nvim-tree",
  ["nvim-treesitter"] = "nvim-treesitter",
  ["nvim-ts-rainbow"] = "nvim-ts-rainbow",
  ["nvim-ts-rainbow2"] = "nvim-ts-rainbow2",
  ["nvim-web-devicons"] = "nvim-web-devicons",
  ["symbols-outline.nvim"] = "symbols-outline",
  ["telescope.nvim"] = "telescope",
  ["vimwiki"] = "vimwiki",
  ["which-key.nvim"] = "which-key",
  ["noice.nvim"] = "noice",
}
