local function callback()
  return {
    DevIconC = { fg = C.icon.c },
    DevIconCss = { fg = C.icon.css },
    DevIconDeb = { fg = C.icon.deb },
    DevIconDockerfile = { fg = C.icon.docker },
    DevIconHtml = { fg = C.icon.html },
    DevIconJpeg = { fg = C.icon.jpeg },
    DevIconJpg = { fg = C.icon.jpg },
    DevIconJs = { fg = C.icon.js },
    DevIconJsx = { fg = C.icon.jsx },
    DevIconKotlin = { fg = C.icon.kt },
    DevIconLock = { fg = C.icon.lock },
    DevIconLua = { fg = C.icon.lua },
    DevIconMp3 = { fg = C.icon.mp3 },
    DevIconMp4 = { fg = C.icon.mp4 },
    DevIconOut = { fg = C.icon.out },
    DevIconPng = { fg = C.icon.png },
    DevIconPy = { fg = C.icon.py },
    DevIconRb = { fg = C.icon.rb },
    DevIconRobots = { fg = C.icon.robots },
    DevIconRpm = { fg = C.icon.rpm },
    DevIconRs = { fg = C.icon.rs },
    DevIconToml = { fg = C.icon.toml },
    DevIconTrueTypeFont = { fg = C.icon.ttf },
    DevIconTs = { fg = C.icon.ts },
    DevIconVue = { fg = C.icon.vue },
    DevIconWebOpenFontFormat = { fg = C.icon.woff },
    DevIconWebOpenFontFormat2 = { fg = C.icon.woff2 },
    DevIconXz = { fg = C.icon.zip },
    DevIconZip = { fg = C.icon.zip },
    DevIconMd = { fg = C.icon.md },
    DevIconPackageJson = { fg = C.icon.pkg },
    DevIconPackageLockJson = { fg = C.icon.pkg },
  }
end

return callback
