local function callback()
  return {
    CmpItemAbbr = { fg = C.text },
    CmpItemAbbrDefault = { fg = C.base },
    CmpItemAbbrDeprecated = { fg = C.subtext1 },
    CmpItemAbbrMatch = { fg = C.surface2 },
    CmpItemAbbrMatchFuzzy = { fg = C.surface2 },
    CmpItemKind = { fg = C.yellow },
    CmpItemKindClass = { link = "@type" },
    CmpItemKindColor = { link = "@constant" },
    CmpItemKindConstant = { link = "@constant" },
    CmpItemKindConstructor = { link = "@constructor" },
    CmpItemKindEnum = { link = "@type" },
    CmpItemKindEnumMember = { link = "@field" },
    CmpItemKindEvent = { link = "@type" },
    CmpItemKindField = { link = "@field" },
    CmpItemKindFile = { link = "@text.uri" },
    CmpItemKindFolder = { link = "@constant" },
    CmpItemKindFunction = { link = "@function" },
    CmpItemKindInterface = { link = "@type" },
    CmpItemKindKeyword = { link = "@keyword" },
    CmpItemKindMethod = { link = "@method" },
    CmpItemKindModule = { link = "@namespace" },
    CmpItemKindOperator = { link = "@operator" },
    CmpItemKindProperty = { link = "@property" },
    CmpItemKindReference = { link = "@type" },
    CmpItemKindSnippet = { link = "@constant" },
    CmpItemKindStruct = { link = "@type" },
    CmpItemKindText = { link = "@text" },
    CmpItemKindTypeParameter = { link = "@type" },
    CmpItemKindUnit = { link = "@constant" },
    CmpItemKindValue = { link = "@constant" },
    CmpItemKindVariable = { link = "@variable" },
    CmpItemMenuDefault = { fg = C.mantle },
  }
end

return callback
