local function callback()
  return {
    TelescopeResultsTitle = { fg = C.green },
    TelescopePromptTitle = { fg = C.blue },
    TelescopePreviewTitle = { fg = C.purple },
    TelescopeResultsBorder = { fg = C.text },
    TelescopePromptBorder = { fg = C.text },
    TelescopePreviewBorder = { fg = C.text },
    TelescopeSelectionCaret = { fg = C.red },
    TelescopeMatching = { fg = C.yellow },
    TelescopeSelection = { bg = C.surface1 },
    TelescopeMultiSelection = { fg = C.blue },
    TelescopeMultiIcon = { fg = C.blue },
    TelescopeNormal = { fg = C.text, bg = C.base },
    TelescopePreviewNormal = { fg = C.text, bg = C.base },
    TelescopePromptNormal = { fg = C.text, bg = C.base },
    TelescopeResultsNormal = { fg = C.text, bg = C.base },
    TelescopeBorder = { fg = C.text },
    TelescopeTitle = { fg = C.text },
    TelescopePromptCounter = { fg = C.subtext0 },
    TelescopePromptPrefix = { fg = C.blue },
    TelescopePreviewLine = { bg = C.surface1 },
    TelescopePreviewMatch = { fg = C.yellow },
    TelescopePreviewPipe = { fg = C.yellow },
    TelescopePreviewCharDev = { fg = C.yellow },
    TelescopePreviewDirectory = { fg = C.blue },
    TelescopePreviewBlock = { fg = C.yellow },
    TelescopePreviewLink = { fg = C.blue },
    TelescopePreviewSocket = { fg = C.purple },
    TelescopePreviewRead = { fg = C.yellow },
    TelescopePreviewWrite = { fg = C.purple },
    TelescopePreviewExecute = { fg = C.green },
    TelescopePreviewHyphen = { fg = C.subtext0 },
    TelescopePreviewSticky = { fg = C.blue },
    TelescopePreviewSize = { fg = C.green },
    TelescopePreviewUser = { fg = C.yellow },
    TelescopePreviewGroup = { fg = C.yellow },
    TelescopePreviewDate = { fg = C.blue },
    TelescopePreviewMessage = { fg = C.text },
    TelescopePreviewMessageFillchar = { fg = C.text },
    TelescopeResultsClass = { fg = C.yellow },
    TelescopeResultsConstant = { fg = C.yellow },
    TelescopeResultsField = { fg = C.red },
    TelescopeResultsFunction = { fg = C.blue },
    TelescopeResultsMethod = { fg = C.blue },
    TelescopeResultsOperator = { fg = C.cyan },
    TelescopeResultsStruct = { fg = C.purple },
    TelescopeResultsVariable = { fg = C.red },
    TelescopeResultsLineNr = { fg = C.subtext0 },
    TelescopeResultsIdentifier = { fg = C.blue },
    TelescopeResultsNumber = { fg = C.orange },
    TelescopeResultsComment = { fg = C.subtext1 },
    TelescopeResultsSpecialComment = { fg = C.subtext0 },
    TelescopeResultsDiffChange = { fg = C.none, bg = C.yellow },
    TelescopeResultsDiffAdd = { fg = C.none, bg = C.green },
    TelescopeResultsDiffDelete = { fg = C.none, bg = C.red },
    TelescopeResultsDiffUntracked = { fg = C.none, bg = C.subtext0 },
  }
end

return callback
